buildscript {
    repositories {
        maven {
            url 'https://dl.bintray.com/giancosta86/Hephaestus'
        }

        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
        classpath 'info.gianlucacosta.moonlicense:moonlicense-gradle:4.3'
        classpath 'info.gianlucacosta.aurora:aurora:7.0'
    }
}


apply plugin: 'scala'
apply plugin: 'maven'
apply plugin: 'com.jfrog.bintray'
apply plugin: 'info.gianlucacosta.moonlicense'
apply plugin: 'info.gianlucacosta.aurora'


group = 'info.gianlucacosta.graphsj'
archivesBaseName = 'graphsj-sdk'
version = '6.1'

description = 'GraphsJ - Scenario Development Kit (SDK)'

project.ext.facebookPage = 'https://www.facebook.com/graphsj'


dependencies {
    generatedCompile 'org.scala-lang:scala-library:2.11.8'

    compile 'org.scala-lang:scala-library:2.11.8'

    compile 'info.gianlucacosta.eighthbridge:eighthbridge:8.2'
    compile 'info.gianlucacosta.lambdaprism:lambdaprism:3.0'
}


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    bintray {
        repo = 'Hephaestus'
        licenses = ['Apache-2.0']
        labels = [
                'GraphsJ',
                'graphs',
                'scenarios',
                'development',
                'SDK',
                'library',
                'Scala'
        ]
    }
}


moonLicense {
    license = apache2

    productInfo {
        productName = 'GraphsJ - SDK'
        inceptionYear = 2009
        copyrightHolder = 'Gianluca Costa'
    }
}
